

spring:
  application:
    name: transfer
  datasource:
    url: jdbc:mysql://192.168.1.140:3306/camel?characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: root
    password: root123
  profiles:
    active: product
  redis:
    database: 0
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.liuxun.transfer.po
