

spring:
  application:
    name: transfer
  datasource:
    url: jdbc:oracle:thin:@192.168.1.130:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: LIUXUN
    password: oracle
  profiles:
    active: product
  redis:
    database: 0
    host: 192.168.1.130
    port: 6379

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.liuxun.transfer.po
logging:
  file: ./transfer.log
  level:
    com.liuxun.transfer.mapper: debug


pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
